site_name: cupid-matching
repo_url: https://github.com/bsalanie/cupid_matching
site_url: https://bsalanie.github.io/cupid_matching
site_description: solves, simulates, and estimates separable matching TU models
site_author: Bernard Salanie
edit_uri: edit/main/docs/
repo_name: bsalanie/cupid-matching
copyright: Maintained by <a href="https://bsalanie.github.io">Bernard Salanie</a>.

nav:
  - Home: index.md
  - API Reference:
      - Minimum Distance Estimator: min_distance.md
      - Utilities for MDE: min_distance_utils.md
      - Poisson estimator: poisson_glm.md
      - Utilities for Poisson: poisson_glm_utils.md
      - Entropy utilities: entropy.md
      - Choo-Siow homoskedastic: choo_siow.md
      - Choo-Siow homoskedastic w/o singles: choo_siow_no_singles.md      
      - Choo-Siow Gender-heteroskedastic: choo_siow_gender_heteroskedastic.md
      - Choo-Siow Heteroskedastic: choo_siow_heteroskedastic.md
      - Nested Logit: nested_logit.md
      - IPFP solvers: ipfp_solvers.md
      - General utliities: utils.md
      - Utilities for Matching: matching_utils.md
      - Classes used: model_classes.md
      - Example on the Choo and Siow model: example_choo_siow.md
      - Example on the Choo and Siow model without singles: example_choo_siow_no_singles.md
      - Example on a nested logit model: example_nested_logit.md
      - Code for a Streamlit app: cupid_streamlit.md
      - Utilities for the Streamlit app: cupid_streamlit_utils.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ..

# theme:
#   palette:
#     scheme: preference

theme:
  name: material
  features:
    - navigation.instant
    - search.highlight
    - navigation.expand
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bsalanie/cupid-matching
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cupid-matching

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - toc:
      permalink: true
  - admonition # add notes, warnings...
  - codehilite
  - toc
  - pymdownx.arithmatex: # for LaTeX
      generic: true
extra_javascript: # for arithmatex
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
